Implemented callback for `input_text_multiline()`
`input_text_multiline()` now takes a Python function as a callback.
The callback function will be wrapped into a C function and passed
into `cimgui.InputTextMultiline` then.

Note that given callback function should return an integer. Otherwise,
an exception would be raised:
```raw
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line XXX, in 'converting callback result'
TypeError: an integer is required (got type NoneType)
```

However, that there are still some issues need to be solved:
- Although callback can be passed into `cimgui.InputTextMultiline`, it
  seems that we still cannot modify text content (`Buf`, which can be
  accessed by `lambda data: data.contents.Buf`) during editing in the
  textbox. Any direct assignment to the member data of `data.contents`
  will make imgui application crash.

- We should avoid re-creating the object `InputTextCallbackWrapper`
  every time `input_text_multiline()` is invoked.